# docs/_config.yml
title: "Martian Terrain Semantic Segmentation"
author: "Georg Tirp"
root: .

only_build_toc_files: true

sphinx:
  extra_extensions:
    - sphinx.ext.autodoc
    - sphinx.ext.napoleon

launch_buttons:
  binderhub_url: "https://mybinder.org"
  colab_url: "https://colab.research.google.com"
  thebe: true

execute:
  execute_notebooks: auto
  exclude_tags:
    - no-exec
  timeout: 600

html:
  extra_css:
    - custom.css
  pygments_style: material
